version: '3.1'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine
    restart: always
    ports:
      - 8001:8000
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer_data:

