# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    #command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856 
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - postgres_local_db:/var/lib/postgresql/data

volumes: 
  postgres_local_db:
